export default [
  {
    path: '/',
    redirect: '/securityResources/equipManage',
  },

  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user',
        routes: [
          {
            name: 'login',
            path: '/user/login',
            component: './user/Login',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    name: '大屏展示',
    icon: 'icon-dapingzhanshi',
    path: `/bigScreen`,
    authority: ['showBigScreen'],
    access: 'normalRouteFilter',
  },
  //AR资源
  {
    name: 'AR资源',
    icon: 'icon-ARziyuan',
    path: '/aresource',
    authority: ['aresource'],
    access: 'normalRouteFilter',
    routes: [
      {
        name: '图层管理',
        path: '/aresource/layer',
        component: './aresource/layer',
        access: 'normalRouteFilter',
        authority: ['layer'],
      },
      {
        name: '图层新增',
        path: '/aresource/layer/add',
        component: './aresource/layer/components/AddEditModel',
        hideInMenu: true,
      },
      {
        name: '场馆管理',
        path: '/aresource/venueManage',
        component: './aresource/venueManage',
        access: 'normalRouteFilter',
        authority: ['venueManage'],
      },
      {
        name: '场馆新增',
        path: '/aresource/venueManage/add',
        component: './aresource/venueManage/add',
        hideInMenu: true,
      },
      {
        name: '场馆编辑',
        path: '/aresource/venueManage/edit',
        component: './aresource/venueManage/add',
        hideInMenu: true,
      },
      {
        name: '场景管理',
        path: '/aresource/sceneManage',
        component: './aresource/sceneManage',

        access: 'normalRouteFilter',
        authority: ['sceneManage'],
      },
      {
        name: '图标管理',
        path: '/aresource/iconManage',
        component: './aresource/iconManage',
        access: 'normalRouteFilter',
        authority: ['iconManage'],
      },
      {
        name: '视频标点管理',
        path: '/aresource/videoPunctuation',
        component: './aresource/videoPunctuation',
        access: 'normalRouteFilter',
        authority: ['videoPunctuation'],
      },
      {
        name: '图层图元管理',
        path: '/aresource/layerunit',
        component: './aresource/layerunit',
        access: 'normalRouteFilter',
        authority: ['layerunit'],
      },
    ],
  },
  //安保资源
  {
    name: '安保资源',
    icon: 'icon-anbaoziyuan',
    path: '/securityResources',
    authority: ['securityResources'],
    access: 'normalRouteFilter',
    routes: [
      {
        name: '基础信息管理',
        path: '/securityResources/keyUnit',
        component: './securityResources/keyUnit',
        authority: ['keyUnitsManage'],
        access: 'normalRouteFilter',
      },
      {
        name: '基础信息管理',
        path: '/securityResources/keyUnit/components/AddUnit',
        component: './securityResources/keyUnit/components/AddUnit',
        hideInMenu: true,
      },
      {
        name: '人员管理',
        path: '/securityResources/personManage',
        component: './securityResources/personManage',
        access: 'normalRouteFilter',
        authority: ['personManage'],
      },
      {
        name: '房屋管理',
        path: '/securityResources/realHouse',
        component: './securityResources/realHouse',
        access: 'normalRouteFilter',
        authority: ['realHouse'],
      },
      {
        name: '装备管理',
        path: '/securityResources/equipManage',
        component: './securityResources/equipManage',
        access: 'normalRouteFilter',
        authority: ['equipManage'],
      },
      {
        name: '停车场管理',
        path: '/securityResources/parkingManage',
        component: './securityResources/parkingManage',
        access: 'normalRouteFilter',
        authority: ['parkingManage'],
      },
      {
        name: '预警设备管理',
        path: '/securityResources/earlyWarnManage',
        component: './securityResources/earlyWarnManage',
        access: 'normalRouteFilter',
        authority: ['earlyWarnManage'],
      },
      {
        name: '停车场新增',
        path: '/securityResources/parkingManage/add',
        component: './securityResources/parkingManage/add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        authority: ['parkingManage'],
      },
      {
        name: '人员新增',
        path: '/securityResources/personManage/addPerson',
        component: './securityResources/personManage/components/UpdatePerson',
        hideInMenu: true,
      },
      {
        name: '人员编辑',
        path: '/securityResources/personManage/editPerson',
        component: './securityResources/personManage/components/UpdatePerson',
        hideInMenu: true,
      },
      {
        name: '监控管理',
        path: '/securityResources/monitorManage',
        component: './securityResources/monitorManage',
        authority: ['monitorManage'],
      },
      {
        name: '监控新增',
        path: '/securityResources/monitorManage/add',
        component: './securityResources/monitorManage/add',
        hideInMenu: true,
        authority: ['monitorManage'],
      },
      {
        name: '卡口管理',
        path: '/securityResources/station',
        component: './securityResources/station',
        authority: ['station'],
      },
    ],
  },
  //安保活动
  {
    name: '安保活动',
    icon: 'icon-anbaohuodong',
    path: '/securityActivities',
    access: 'normalRouteFilter',
    authority: ['securityActivities'],
    routes: [
      {
        name: '活动管理',
        path: '/securityActivities/activityManage',
        component: './securityActivities/activityManage',
        authority: ['activityManage'],
        access: 'activityManage',
      },
      {
        name: '活动新增',
        path: '/securityActivities/activityManage/add',
        component: './securityActivities/activityManage/add',
        access: 'normalRouteFilter',
        authority: ['activityManage'],
        hideInMenu: true,
      },
      {
        name: '预案管理',
        path: '/securityActivities/prepar',
        component: './securityActivities/prepar',
        access: 'normalRouteFilter',
        authority: ['reservePlan'],
      },
      {
        name: '预案推演管理',
        path: '/securityActivities/yaty',
        component: './securityActivities/yaty',
        access: 'normalRouteFilter',
        authority: ['yatyManage'],
      },
      {
        name: '值班管理',
        path: '/securityActivities/duty',
        component: './securityActivities/duty',
        access: 'normalRouteFilter',
        authority: ['onDutyManage'],
      },
      {
        name: '值班管理新增',
        path: '/securityActivities/duty/components/Add',
        component: './securityActivities/duty/components/Add',
        hideInMenu: true,
      },
      {
        name: '嘉宾管理',
        path: '/securityActivities/guest',
        component: './securityActivities/guest/guest',
        access: 'normalRouteFilter',
        authority: ['guestManage'],
      },
      {
        name: '赛事管理',
        path: '/securityActivities/match',
        component: './securityActivities/match',
        access: 'normalRouteFilter',
        authority: ['match'],
      },
      {
        name: '班车管理',
        path: '/securityActivities/car',
        component: './securityActivities/car',
        access: 'normalRouteFilter',
        authority: ['car'],
      },
      {
        name: '岗位任务',
        path: '/securityActivities/task',
        component: './securityActivities/task',
        access: 'normalRouteFilter',
        authority: ['task'],
      },
      {
        name: '任务管理',
        path: '/securityActivities/duties',
        component: './securityActivities/duties',
        access: 'normalRouteFilter',
        authority: ['duties'],
      },
      {
        name: '票务管理',
        path: '/securityActivities/ticket',
        component: './securityActivities/ticket',
        access: 'normalRouteFilter',
        authority: ['ticket'],
      },
    ],
  },
  //系统管理
  {
    name: '系统管理',
    icon: 'icon-xitongguanli',
    path: '/systemManager',
    access: 'normalRouteFilter',
    authority: ['systemManage'],
    routes: [
      {
        name: '组织架构管理',
        path: '/systemManager/organization',
        component: './systemManager/organization',

        access: 'normalRouteFilter',
        authority: ['organization'],
      },
      {
        name: '权限管理',
        path: '/systemManager/authorityManager',
        component: './systemManager/authorityManager',
        access: 'normalRouteFilter',
        authority: ['authorityManager'],
      },
      {
        name: '用户管理',
        path: '/systemManager/personManagement',
        component: './systemManager/personManagement',
        access: 'normalRouteFilter',
        authority: ['personManagement'],
      },
      {
        name: '分类管理',
        path: '/systemManager/flManagement',
        component: './systemManager/flManagement',

        access: 'normalRouteFilter',
        authority: ['flManagement'],
      },
      {
        name: '区域管理',
        path: '/systemManager/regionManagement',
        component: './systemManager/regionManagement',

        access: 'normalRouteFilter',
        authority: ['regionManagement'],
      },
      {
        name: '数据域管理',
        path: '/systemManager/dataFieldManager',
        component: './systemManager/dataFieldManager',

        access: 'normalRouteFilter',
        authority: ['dataFieldManager'],
      },
      {
        name: '角色管理',
        path: '/systemManager/rolerManagement',
        component: './systemManager/rolerManagement',

        access: 'normalRouteFilter',
        authority: ['rolerManagement'],
      },
      {
        name: '字典管理',
        path: '/systemManager/dictManagement',
        component: './systemManager/dictManagement',

        access: 'normalRouteFilter',
        authority: ['dictManagement'],
      },
      {
        name: '操作日志',
        path: '/systemManager/systemJournal',
        component: './systemManager/systemJournal',
        access: 'normalRouteFilter',
        authority: ['systemJournal'],
      },
      {
        name: '附件管理',
        path: '/systemManager/attachManagement',
        component: './systemManager/attachManagement',

        access: 'normalRouteFilter',
        authority: ['attachManagement'],
      },
      {
        name: '用户新增',
        path: '/systemManager/personManagement/addPerson',
        component: './systemManager/personManagement/components/AddPerson',
        hideInMenu: true,
      },
      {
        name: '用户编辑',
        path: '/systemManager/personManagement/editPerson',
        component: './systemManager/personManagement/components/AddPerson',
        hideInMenu: true,
      },
      {
        name: '用户详情',
        path: '/systemManager/personManagement/detailPerson',
        component: './systemManager/personManagement/components/DetailPerson',
        hideInMenu: true,
      },
      {
        name: '角色新增',
        path: '/systemManager/rolerManagement/addRoler',
        component: './systemManager/rolerManagement/components/AddRoler',
        hideInMenu: true,
      },
      {
        name: '角色编辑',
        path: '/systemManager/rolerManagement/editRoler',
        component: './systemManager/rolerManagement/components/AddRoler',
        hideInMenu: true,
      },
      {
        name: '用户新增',
        path: '/systemManager/personManagement/addPerson',
        component: './systemManager/personManagement/components/AddPerson',
        hideInMenu: true,
      },
      {
        name: '用户编辑',
        path: '/systemManager/personManagement/editPerson',
        component: './systemManager/personManagement/components/AddPerson',
        hideInMenu: true,
      },
      // {
      //   name: '附件新增',
      //   path: '/systemManager/attachManagement/addAttach',
      //   component: './systemManager/attachManagement/components/AttachOpera',
      //   hideInMenu: true,
      // },
      // {
      //   name: '附件编辑',
      //   path: '/systemManager/attachManagement/editAttach',
      //   component: './systemManager/attachManagement/components/AttachOpera',
      //   hideInMenu: true,
      // },
      // {
      //   name: '附件详情',
      //   path: '/systemManager/attachManagement/attachOpera',
      //   component: './systemManager/attachManagement/components/AttachOpera',
      //   hideInMenu: true,
      // },
    ],
  },
  {
    component: './404',
  },
];
